### ISSUE TITLE
Node hangs completly

### ISSUE THREAD

**Issue by lkovacs74** [matt-kruse/find-my-iphone#15]
Dear Matt,

Installed this node to my node red. This is a clean and new installation on a Rasspberry Jessie.
It reads the devices correctly, but hangs with this error message:

12 Mar 17:44:08 - [red] Uncaught Exception:
12 Mar 17:44:08 - TypeError: Cannot call method 'map' of undefined
    at /home/pi/.node-red/node_modules/node-red-contrib-find-my-iphone/find-my-i                                                                                                     phone.js:31:28
    at /home/pi/.node-red/node_modules/node-red-contrib-find-my-iphone/node_modu                                                                                                     les/find-my-iphone/index.js:119:12
    at /home/pi/.node-red/node_modules/node-red-contrib-find-my-iphone/node_modu                                                                                                     les/find-my-iphone/index.js:40:14
    at Request._callback (/home/pi/.node-red/node_modules/node-red-contrib-find-                                                                                                     my-iphone/node_modules/find-my-iphone/index.js:67:12)
    at Request.self.callback (/home/pi/.node-red/node_modules/node-red-contrib-f                                                                                                     ind-my-iphone/node_modules/find-my-iphone/node_modules/request/request.js:188:22                                                                                                     )
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/pi/.node-red/node_modules/node-red-contrib-fin                                                                                                     d-my-iphone/node_modules/find-my-iphone/node_modules/request/request.js:1171:10)
    at Request.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/home/pi/.node-red/node_modules/node-red-con                                                                                                     trib-find-my-iphone/node_modules/find-my-iphone/node_modules/request/request.js:                                                                                                     1091:12)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)

Could you chek why hanging?

Thanks,
L

**Comment by FlorianWendelborn** [comment]
What's your code?

**Comment by lkovacs74** [comment]
HI,

I can't have a code, I just put the F-M-I node on my node red and connect to a debug, which send the whole message to the debug window. That's all what I did.

Thakns,
L

**Comment by FlorianWendelborn** [comment]
The thing is that the error you're encountering is thrown by node red, not by `find-my-iphone`. `find-my-iphone` doesn't have the `.map()` method in its source code.

**Comment by omnibrain** [comment]
I created a MR that should fix the problem. Basically this error occurs if the HTTP request to the icloud api failed. I will add a check in the node-red plugin that prevents it from crashing, but as soon as above MR is merged, the error should not occur anymore.
